### ISSUE TITLE
TypeError: getattr(): attribute name must be string

### ISSUE THREAD

**Issue by hengliangzhu** [lightaime/deep_gcns_torch#6]
Thank you for your good work！
But when training，i get some errors

Traceback (most recent call last):
  File "sem_seg/train.py", line 141, in <module>
    main()
  File "sem_seg/train.py", line 61, in main
    train(model, train_loader, optimizer, scheduler, criterion, opt)
  File "sem_seg/train.py", line 81, in train
    out = model(data)
  File "/root/anaconda3/envs/deepgcn37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/dgdr250/hd/hyydown/deep_gcns_torch/models/architecture.py", line 105, in forward
    feats = [self.head(inputs, self.knn(inputs[:, 0:3]))]
  File "/root/anaconda3/envs/deepgcn37/lib/python3.7/site-packages/torch_geometric/data/data.py", line 92, in __getitem__
    return getattr(self, key, None)
TypeError: getattr(): attribute name must be string

Can you kindly tell me how to solve it?
Many thanks!!!

**Comment by guochengqian** [comment]
@hengliangzhu  Thanks for pointing out the issue. We just notice this is the issue with the sparse data format. I already push the new code, please check.

**Comment by guochengqian** [comment]
@hengliangzhu  Hello. I believe the bug is fixed now.

**Comment by hengliangzhu** [comment]
Thank you very much, i will have a try....
