### ISSUE TITLE
RuntimeError: The following operation failed in the TorchScript interpreter + CUDA OOM

### ISSUE THREAD

**Issue by xo28** [lightaime/deep_gcns_torch#90]
Hi, I try to run the ogbn-arxiv example but end up getting this error:
```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/data5/xo2/.conda/envs/deepgcn/lib/python3.8/site-packages/torch_scatter/composite/softmax.py", line 16, in scatter_softmax
    index = broadcast(index, src, dim)

    max_value_per_index = scatter_max(src, index, dim=dim)[0]
                          ~~~~~~~~~~~ <--- HERE
    max_per_src_element = max_value_per_index.gather(dim, index)
  File "/data5/xo2/.conda/envs/deepgcn/lib/python3.8/site-packages/torch_scatter/scatter.py", line 79, in scatter_max
        out: Optional[torch.Tensor] = None,
        dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: CUDA out of memory. Tried to allocate 2.37 GiB (GPU 0; 10.76 GiB total capacity; 6.39 GiB already allocated; 1.35 GiB free; 8.42 GiB reserved in total by PyTorch)
```
It's weird because I'm using the default setting in Readme and this error will disappear when it runs on CPU. 
The GPU I'm using is vacant but there's also a CUDA OOM error, any suggestions on this one?

The full Traceback is here:
```
Traceback (most recent call last):
  File "/data5/xo2/deep_gcns_torch/examples/ogb/ogbn_arxiv/main.py", line 127, in <module>
    main()
  File "/data5/xo2/deep_gcns_torch/examples/ogb/ogbn_arxiv/main.py", line 98, in main
    epoch_loss = train(model, x, edge_index, y_true, train_idx, optimizer)
  File "/data5/xo2/deep_gcns_torch/examples/ogb/ogbn_arxiv/main.py", line 42, in train
    pred = model(x, edge_index)[train_idx]
  File "/data5/xo2/.conda/envs/deepgcn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data5/xo2/deep_gcns_torch/examples/ogb/ogbn_arxiv/model.py", line 96, in forward
    res = checkpoint(self.gcns[layer], h2, edge_index)
  File "/data5/xo2/.conda/envs/deepgcn/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 163, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/data5/xo2/.conda/envs/deepgcn/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 74, in forward
    outputs = run_function(*args)
  File "/data5/xo2/.conda/envs/deepgcn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data5/xo2/deep_gcns_torch/gcn_lib/sparse/torch_vertex.py", line 67, in forward
    m = self.propagate(edge_index, x=x, edge_attr=edge_emb)
  File "/data5/xo2/.conda/envs/deepgcn/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 253, in propagate
    out = self.aggregate(out, **aggr_kwargs)
  File "/data5/xo2/deep_gcns_torch/gcn_lib/sparse/torch_message.py", line 55, in aggregate
    out = scatter_softmax(inputs*self.t, index, dim=self.node_dim)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/data5/xo2/.conda/envs/deepgcn/lib/python3.8/site-packages/torch_scatter/composite/softmax.py", line 16, in scatter_softmax
    index = broadcast(index, src, dim)

    max_value_per_index = scatter_max(src, index, dim=dim)[0]
                          ~~~~~~~~~~~ <--- HERE
    max_per_src_element = max_value_per_index.gather(dim, index)
  File "/data5/xo2/.conda/envs/deepgcn/lib/python3.8/site-packages/torch_scatter/scatter.py", line 79, in scatter_max
        out: Optional[torch.Tensor] = None,
        dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: CUDA out of memory. Tried to allocate 2.37 GiB (GPU 0; 10.76 GiB total capacity; 6.39 GiB already allocated; 1.35 GiB free; 8.42 GiB reserved in total by PyTorch)
```
Thank you!!!

**Comment by lightaime** [comment]
We ran the experiments on one v100 with 32G memory. Perhaps 28 layers are too deep for 11G. Could you try to make it shallower?

**Comment by xo28** [comment]
Thanks for your reply! I've tried reducing the number of layers to 1. But the same error occurs again and it tries to allocate the same amount of memory as 28 layers.
```
The number of layers 1 Aggregation method softmax_sg block: res+
LN/BN->ReLU->GraphConv->Res
08/04 09:44:06 AM DeeperGCN(
  (gcns): ModuleList(
    (0): GENConv(
      (mlp): MLP(
        (0): Linear(in_features=128, out_features=128, bias=True)
      )
      (msg_encoder): ReLU()
    )
  )
  (norms): ModuleList(
    (0): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (node_features_encoder): Linear(in_features=128, out_features=128, bias=True)
  (node_pred_linear): Linear(in_features=128, out_features=40, bias=True)
)
Traceback (most recent call last):
  File "/data5/xo2/deep_gcns_torch/examples/ogb/ogbn_arxiv/main.py", line 127, in <module>
    main()
  File "/data5/xo2/deep_gcns_torch/examples/ogb/ogbn_arxiv/main.py", line 98, in main
    epoch_loss = train(model, x, edge_index, y_true, train_idx, optimizer)
  File "/data5/xo2/deep_gcns_torch/examples/ogb/ogbn_arxiv/main.py", line 42, in train
    pred = model(x, edge_index)[train_idx]
  File "/data5/xo2/anaconda3/envs/deepgcn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data5/xo2/deep_gcns_torch/examples/ogb/ogbn_arxiv/model.py", line 86, in forward
    h = self.gcns[0](h, edge_index)
  File "/data5/xo2/anaconda3/envs/deepgcn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data5/xo2/deep_gcns_torch/gcn_lib/sparse/torch_vertex.py", line 67, in forward
    m = self.propagate(edge_index, x=x, edge_attr=edge_emb)
  File "/data5/xo2/anaconda3/envs/deepgcn/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 253, in propagate
    out = self.aggregate(out, **aggr_kwargs)
  File "/data5/xo2/deep_gcns_torch/gcn_lib/sparse/torch_message.py", line 55, in aggregate
    out = scatter_softmax(inputs*self.t, index, dim=self.node_dim)
  File "/data5/xo2/anaconda3/envs/deepgcn/lib/python3.7/site-packages/torch_scatter/composite/softmax.py", line 15, in scatter_softmax
    max_value_per_index = scatter_max(src, index, dim=dim)[0]
  File "/data5/xo2/anaconda3/envs/deepgcn/lib/python3.7/site-packages/torch_scatter/scatter.py", line 73, in scatter_max
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
RuntimeError: CUDA out of memory. Tried to allocate 2.37 GiB (GPU 0; 10.76 GiB total capacity; 3.76 GiB already allocated; 2.22 GiB free; 3.76 GiB reserved in total by PyTorch)
```

**Comment by lightaime** [comment]
Hi @xo28, it seems this is because your GPU memory is too small. But for 11G GPU I was able to run 14 layers with 64 hidden channels.
Could you try to run the following setting?
`python main.py --use_gpu --self_loop --num_layers 14 --block res+ --gcn_aggr softmax_sg --t 0.1 --hidden_channels 64`

**Comment by lightaime** [comment]
If you want to reduce the memory complexity for running deep models, you can also check our recent ICML paper: https://arxiv.org/abs/2106.07476 with code available on https://github.com/lightaime/deep_gcns_torch/tree/master/examples/ogb_eff.
